#!/bin/bash
echo "════════════════════════════════════════════════════════"
echo "   GitHub Push Instructions"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Repository: fadil369/sbs"
echo "Commit: 1ceb2f0 (49 files changed)"
echo "Branch: main"
echo ""
echo "Option 1: Push with Personal Access Token (PAT)"
echo "─────────────────────────────────────────────────"
echo "1. Create PAT at: https://github.com/settings/tokens"
echo "   - Select: repo (full control)"
echo "   - Generate and copy token"
echo ""
echo "2. Run:"
echo "   cd /root/sbs-github"
echo "   git push https://YOUR_TOKEN@github.com/fadil369/sbs.git main"
echo ""
echo "Option 2: Push with SSH Key"
echo "─────────────────────────────────────────────────"
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C 'dr.mf.12298@gmail.com'"
echo ""
echo "2. Add to GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   # Copy and add at: https://github.com/settings/keys"
echo ""
echo "3. Change remote and push:"
echo "   cd /root/sbs-github"
echo "   git remote set-url origin git@github.com:fadil369/sbs.git"
echo "   git push origin main"
echo ""
echo "Option 3: Manual Push via GitHub CLI"
echo "─────────────────────────────────────────────────"
echo "   gh auth login"
echo "   cd /root/sbs-github"
echo "   gh repo sync"
echo ""
echo "════════════════════════════════════════════════════════"
echo "Current Status:"
echo "  ✅ All changes committed locally"
echo "  ⏳ Waiting for authentication to push"
echo "════════════════════════════════════════════════════════"
